### ISSUE TITLE
Gamemode Bug

### ISSUE THREAD

**Issue by w1nst0nDEV** [Butzlabben/worldsystem#18]
**Users can easily get gamemode creative:** When a player creates a world, they are put into creative (by default) when they join their own world. When the exit the world, for example, they teleport back to spawn with an external /spawn command, they are still in that gamemode they were in. Here's how to fix:

- Only allow players to change their gamemode/teleport to players in their world or worlds they have access to do so in.
- Save their current gamemode and location in the world they were in before they get teleported to a world.
- When the player leaves the world due to an external command, change their gamemode to what it was before they teleported to their world.
- If a player leaves with **/ws leave**, they are teleported back to where they were when they executed the command /ws home or any other command. They are also placed in the gamemode they were at before executing the command.

Thanks!

**Comment by w1nst0nDEV** [comment]
**Sidenote:** This is different than a normal /ws delete or leave. When a player is teleported outside of the world via an external command, their gamemode doesn't change.

**Comment by Butzlabben** [comment]
Should be fixed with new version. Update soon
