### ISSUE TITLE
Cannot get player to spawn at last location after world logout

### ISSUE THREAD

**Issue by tankpillow** [Butzlabben/worldsystem#22]
There is a bug where  the player always spawns into their player world at 0, 0. instead of spawning at their last location. Is this a bug or is there a setting to change that in the config that I missed.

**Comment by Butzlabben** [comment]
There is a configoption named "worldspawn" in the config.yml

**Comment by tankpillow** [comment]
I'm still getting the problem. This is what I have in my config:

`##########################################################################
### __              __         __    _______          __               ###
### \ \            / /        / /   / / ___/         / /               ###
###  \ \    __    / /___  ___/ /___/ / /____  ______/ /______________  ###
###   \ \  /  \  / / __ \/ _/ / __  /__  / / / / __/ __/ ___/ _  _  /  ###
###    \ \/ /\ \/ / /_/ / // / /_/ /__/ / /_/ /_  / /_/ ___/ // // /   ###
###     \__/  \__/\____/_//_/\__,_/____/\__, /___/\__/\___/_//_//_/    ###
###                                    ___/ /                          ###
###                                    \___/                           ###
##########################################################################

# Path where the worlds will be saved
worldfolder: 'plugins/WorldSystem/Worlds'

worldtemplates:
  # Wheter players can decide on different templates
  multi_choose: false
  # If multi_choose is disabled, which template should be choosen
  default: 'template_default'
  templates:
    # The "1" can be any key
    1: 
      # Name of directory in plugins/WorldSystem/worldsources
      # e.g. this would be plugins/WorldSystem/worldsources/template_default
      name: 'template_default'
      # Just remove the permission field if everybody should be able to use this template
    2:
      name: 'another_template'
      # Only players with this exact permission can use and see this template
      # ws.* will not work with this
      permission: ws.template.another_template

# If a confirm is needed before auto-update
need_confirm: true

# When nobody is on a world time until it get unloaded
unloadingtime: 20

# If true nobody can teleport or change their gamemode a WorldSystem world
# Except for players with the permissions: ws.gamemode | ws.tp.*
survival: true

# If true players will teleported to the spawn on join
spawn_teleportation: false

# Time in seconds until a request expires
request_expires: 20

# Name of the languagefile in plugins/WorldSystem/messages/
language: en

# Prefix which will be shown before each message
prefix: '&8[&3SkyboxMC&8] &6'

# Time in days after a not used world will be deleted
# Set to -1 to disable
delete_after: -1

# Whether WorldSystem should contact the Mojang authserver
# If not, some unknown playernames will not be displayed
# eg. in the gui or in /ws info
contact_authserver: true

# Options for the LagSystem:
# period_in_seconds - how often will be checked for entities in seconds
# entities_per_world - maximal allowed entities per world
# garbagecollector - how often will be unused ram be cleared
lagsystem:
  period_in_seconds: 10
  entities_per_world: 350
  garbagecollector:
    use: false
    period_in_minutes: 5
    
# Options for random world generation
worldgeneration:
  # A seed for worldgeneration
  # Set it to 0 for no seed-useage
  seed: 0
  # Environment for the world
  # Valid inputs are 'NORMAL', 'NETHER' and 'THE_END'
  environment: NORMAL
  # Type of the world eg. flat, amplified, ...
  # Valid types are 'NORMAL', 'VERSION_1_1', 'FLAT', 'AMPLIFIED', 'CUSTOMIZED' or 'LARGE_BIOMES'
  type: VERSION_1_1
  # Put in here the name of a generator
  # If you have one from one plugin
  generator: ''

# Location where you will be teleported when you leave you world
spawn:
  gamemode: 2
  spawnpoint:
    world: world
    x: 0
    y: 20
    z: 0
    yaw: 0
    pitch: 0

# Location where you spawn when you join a world
worldspawn:
  use: false
  spawnpoint:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
`

**Comment by Butzlabben** [comment]
You will then be teleported to world spawn of the world (/setworldspawn). Do you have a template or do you generate them?

**Comment by tankpillow** [comment]
When I do /spawn or /ws leave I teleport to the world spawn. I did not use the /setworldspawn command. I do not have a template, I'm using the default one

**Comment by Butzlabben** [comment]
Ohhh, now I get your issue. It is the „spawn“ option.

**Comment by tankpillow** [comment]
Sorry, I dont understand

**Comment by Butzlabben** [comment]
You have to configure the „spawn“ option in the config.yml

**Comment by tankpillow** [comment]
Wait, this?

spawn:
  gamemode: 2
  spawnpoint:
    world: world
    x: 0
    y: 20
    z: 0
    yaw: 0
    pitch: 0

**Comment by Butzlabben** [comment]
Yes

**Comment by tankpillow** [comment]
What do I have to change there? Does that only affect the spawn world? or the player worlds?

**Comment by Butzlabben** [comment]
It affects the spawn world

**Comment by tankpillow** [comment]
I don't think that is my problem. It is the when a player returns to "world", and when they teleport back to their private world they spawn at 0 0 no matter where they left off. 

config.yml
spawn:
  gamemode: 2
  spawnpoint:
    world: world
    x: 0
    y: 20
    z: 0
    yaw: 0
    pitch: 0
worldspawn:
  use: false
  spawnpoint:
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0

**Comment by Butzlabben** [comment]
Please send the whole „WorldSystem“ folder as a.zip file to me.

**Comment by tankpillow** [comment]
alright.
[plugins_WorldSystems.zip](https://github.com/Butzlabben/worldsystem/files/2898465/plugins_WorldSystems.zip)

**Comment by Butzlabben** [comment]
The bug was not reproducible on my local testserver (1.13). After leaving with /ws leave and return back with /ws home it worked with any flaws. Maybe consider to delete the old worlds

**Comment by tankpillow** [comment]
I tried deleting the the old worlds. Im still getting the same problem,

**Comment by Butzlabben** [comment]
Will be fixed when #23 is implemented

**Comment by Butzlabben** [comment]
Please send the whole server as a zip. Unfortunately I am next week on vacation and can’t do anything. But if maybe someone else could test it?
Maybe try to delete some plugins.

**Comment by tankpillow** [comment]
I tried uploading the file directly however its to big so I uploaded it to dropbox here is the link:

[https://www.dropbox.com/s/j9wkomcfwtsl2af/WorldSystems.zip?dl=0](url)

**Comment by Butzlabben** [comment]
@EsGibtKeineMitte could you please test for this issue?

**Comment by Butzlabben** [comment]
Ok, I tested it myself with this server configuration. 
I joined and did /ws get, I timed out (poor computer) and my world was created. I joined and was teleported to 0 20 0 on the the world "world". **This issue can be fixed with the spawn property in the config.yml**
Then I joined my own world with /ws home and was teleported to the right spot.

**Comment by tankpillow** [comment]
Alright what would I change in the config. Not sure what you mean by spawn property

**Comment by Butzlabben** [comment]
![notepad++_2019-03-09_17-33-01](https://user-images.githubusercontent.com/29730180/54074348-b4a64f00-4291-11e9-9c0f-1f7a618a0cd1.png)

**Comment by Butzlabben** [comment]
Were you able to fix it?

**Comment by tankpillow** [comment]
Sorry didn’t have a chance to test it earlier, but no it did not fix it.

**Comment by tankpillow** [comment]
can you by any chance send me files of won that works for you?

**Comment by Butzlabben** [comment]
Download link: https://we.tl/t-i7FnarLp9F
If you encounter the error again, please make a screen recording so I can see all steps.

**Comment by Butzlabben** [comment]
Does it work now?
If so, please remove the two-star rating and leave a 5-star review.
This issue will be closed in two days if no other comments.

**Comment by Butzlabben** [comment]
Should also be fixed with new issue.
