### ISSUE TITLE
PlaceholderAPI Implementation

### ISSUE THREAD

**Issue by w1nst0nDEV** [Butzlabben/worldsystem#25]
**Hey!** Could you please add PlaceholderAPI implementation? I have some ideas for a few placeholders:

- **%has_created_world%:** This returns a boolean of whether or not a player has created a world with /ws get.
- **%is_creator_of_world%:** This returns a boolean of whether or not a player is the creator of the world. This could be useful if anyone were to program a command, but to use the command, the player has to be in the world they own.
- **%creators_world_name%:** This returns a string of the name of the world the player owns. This returns `none` if the person hasn't created a world.
- **%creators_world_loaded%:** This returns whether or not their world is loaded. This returns `none` if the person hasn't created a world.

PlaceholderAPI implementation allows for a large range of possibilities. I, along with your community, would love it if it were implemented! Thank you!

**Comment by Butzlabben** [comment]
Is implemented now
See: https://github.com/Butzlabben/worldsystem/wiki/PlaceholderAPI-support
