### ISSUE TITLE
error on world load

### ISSUE THREAD

**Issue by aglarcz** [Butzlabben/worldsystem#33]
**Describe the bug**
Error in the console: https://pastebin.com/raw/4FF0QUCR

**To Reproduce**
Create new world or load old one via for example /ws home - error appears in console.

On latest paperspigot 1.14.4 #154 and worldsystem 2.4.6.

**Comment by Butzlabben** [comment]
It looks like, that the process took too long. Does the error also appear on paperspigot 1.14.3?

**Comment by Butzlabben** [comment]
This occurs because it takes so long to create/load a world
