### ISSUE TITLE
SQLite Error

### ISSUE THREAD

**Issue by cleme29** [Butzlabben/worldsystem#34]
**Describe the bug**
When I connect to the server, this error appears in the console : https://pastebin.com/sHAh67nj

**To Reproduce**
Just start the server with the plugin installed with no configuration so it generates it.

**Expected behavior**
Don't spawn at 0,20,0 at log in. And keep tracking positions of players both in their world and as well as in the over-world when they go back and forth with the /ws home & /ws leave.

**Additional context**
File permissions are fine and I tried both SQLite and MariaDB with no changes whatsoever.

**Comment by Butzlabben** [comment]
Btw this was a really good issue description. Next time provide some more version information. But except this, this issue was really nice.

**Comment by cleme29** [comment]
Yes sorry I've done it before but I opt in the new github dupe issue thingy and it erases everything I wrote :( And ofc I was too lazy to retype everything :D
