### ISSUE TITLE
Feature request: Player should be able to delete his own world

### ISSUE THREAD

**Issue by denis-ev** [Butzlabben/worldsystem#45]
**Is your feature request related to a problem? Please describe.**
Player can't delete his own world

**Describe the solution you'd like**
/ws delete (without {playername} tries to delete own world

**Comment by Butzlabben** [comment]
Please send a video as proof. This shouldn't be possible at all.

**Comment by denis-ev** [comment]
@Butzlabben okay, you misread it. 
It’s not a bug, but a feature request.

**Comment by Butzlabben** [comment]
Why should players want to delete their own world? If they want a new one, they can do /ws reset

**Comment by denis-ev** [comment]
What if there are multiple worlds to choose from? 
With reset they can only reset the one and never switch worlds.

**Comment by Butzlabben** [comment]
If they reset their world, they are able to choose one the template.
