### ISSUE TITLE
FAWE | AsyncWorld Dependency

### ISSUE THREAD

**Issue by xXSchrandXx** [Butzlabben/worldsystem#52]
Ich glaube, hiermit kannst du auch AsyncWorld ohne [systemPath](https://github.com/Butzlabben/worldsystem/blob/0633d9c7f79485dd0a8e973a6cffc537128c0316/pom.xml#L145) benutzen.

``` xml
<!-- FAWE-Bukkit Dependency -->
<dependency>
<groupId>com.boydti</groupId>
<artifactId>fawe-bukkit</artifactId>
<!-- https://ci.athion.net/job/FastAsyncWorldEdit/ws/mvn/com/boydti/fawe-bukkit/ -->
<version>19.11.13-5505943-1282-22.3.5</version>
</dependency>
```

**Comment by Butzlabben** [comment]
It does not work. I have tested it. Then the TasKmanager would be missing
