### ISSUE TITLE
[Bug] Using your latest build

### ISSUE THREAD

**Issue by MrPranklez** [Butzlabben/worldsystem#54]
**Describe the bug**
World is not created. Seems to be an issue relating to something with FAWE? Using this on my creative server with the latest build of PlotSquared and FAWE.

**To Reproduce**
- Set up a 1.15.2 server with worldsystem, plotsquared and fawe (latest builds)
- make sure async world creation is enabled in config.yml
- run /ws get
- error will be visible in console

**Expected behavior**
The world to be generated as it should

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Error:**
https://hastebin.com/ifuvoxiquf.md

**Comment by MrPranklez** [comment]
auto updater also thinks this isn't the latest build although the versions are the exact same:
https://gyazo.com/7115350dcad0e5a5003df7e2307f41ca

**Comment by jensuenk** [comment]
Same problem for me on version 1.15.2. Is this related to fawe or worldsystem?
`java.lang.IllegalStateException: WorldInitEvent may only be triggered synchronously.`

**Comment by Butzlabben** [comment]
Now only in version 1.8 -  1.12 worlds can be created async
